### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by CG-man** [arthurkiller/electronic-QQ#9]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at AppTray.createTray (/home/cg-man/下载/electronic-QQ-master/src/windows/controllers/app_tray.js:48:15)
    at AppTray.fs.readFile (/home/cg-man/下载/electronic-QQ-master/src/windows/controllers/app_tray.js:31:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

**Comment by arthurkiller** [comment]
Sorry for bugs bro ,and I will release a basic vision before chinese new year @CG-man
